title: Raspberry Pi - Motion Sensor
hero_image: images/banner.png
description: Connect a passive infrared motion sensor to your Raspberry Pi!
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Passive Infra-red (PIR) Motion Sensors
    completion:
    - engaged
  - title: Detect motion with a PIR
    completion:
    - internal
 - title: What can you do now?
    completion:
    - external